server:
  port: 8090
  servlet:
    context-path: /user-service

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost/user-service
    username: root
    password: admin1234
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
jwt:
  secret: ${KEYSECRET_SECURITY:5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437}
  expiration: ${EXPIRE_DAYS_SECURITY:3600000}

management:
  endpoints:
    web:
      exposure:
        include: "*"

